[package]
name = "ic_play"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ic-agent = {version="0.7.0", features=["reqwest"] }
ic-utils = "0.5.0"
tokio = { version = "1", features = ["full"] }